name: AutoTestApp

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  upload-apk:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 检查 APK 文件是否存在
      - name: Check APK existence
        run: |
          if [ ! -f "apk/app-newest.apk" ]; then
            echo "APK 文件不存在！"
            exit 1
          fi

      # 3. 调用 Testin 登录接口并提取 result 值
      - name: 调用 Testin 登录接口
        id: login
        run: |
          TIMESTAMP=$(date +%s%3N)
          REQUEST_DATA=$(cat <<EOF
          {
            "apikey": "0cc70ef717d01b48ebfef5868a60cdd9",
            "mkey": "usermanager",
            "op": "Login.login",
            "data": {
              "email": "nibingbing@testin.cn",
              "pwd": "9624564eebc9a3c388f29598779f6215"
            },
            "action": "user",
            "timestamp": ${TIMESTAMP}
          }
          EOF
          )
          RESPONSE=$(curl -s -X POST "https://openapizyy.testin.cn" \
            -H "Content-Type: application/json" \
            -d "$REQUEST_DATA")
          echo "登录接口返回结果：$RESPONSE"
          RESULT=$(echo "$RESPONSE" | grep -o '"result":"[^"]*"' | awk -F':' '{print $2}' | sed 's/"//g')
          if [ -z "$RESULT" ]; then
            echo "未提取到有效的 result 值！"
            exit 1
          fi
          echo "::set-output name=result::$RESULT"

      # 4. 使用提取到的 result 值上传 APK 文件
      - name: 上传 APK 文件
        run: |
          # 打印登录返回的 sid 值
          SID=${{ steps.login.outputs.result }}
          echo "登录返回的 sid 值：$SID"

          # 动态生成时间戳
          TIMESTAMP=$(date +%s%3N)

          # 构造 UPLOAD-JSON 头
          UPLOAD_JSON='{"apikey":"0cc70ef717d01b48ebfef5868a60cdd9","timestamp":'"${TIMESTAMP}"',"sid":"'"${SID}"'","sig":"4293d51043aee7e809c69b327848b35f","mkey":"fs","action":"fs","op":"File.upload","data":{"suffix":"apk"}}'
          echo "构造的 UPLOAD-JSON 头：$UPLOAD_JSON"

          # 使用 curl -v 打印详细请求日志
          UPLOAD_RESPONSE=$(curl -v -X POST "https://openapizyy.testin.cn" \
            -H "UPLOAD-JSON: $UPLOAD_JSON" \
            -F "file=@apk/app-newest.apk")

          # 打印上传接口返回结果
          echo "上传接口返回结果："
          echo "$UPLOAD_RESPONSE"

          # 解析返回值（假设返回 JSON 格式）
          STATUS=$(echo "$UPLOAD_RESPONSE" | jq -r '.status')
          MESSAGE=$(echo "$UPLOAD_RESPONSE" | jq -r '.message')
          FILE_ID=$(echo "$UPLOAD_RESPONSE" | jq -r '.file_id')

          # 打印解析后的返回值
          echo "上传状态：$STATUS"
          echo "上传消息：$MESSAGE"
          echo "文件 ID：$FILE_ID"

          # 错误处理
          if [ "$STATUS" != "success" ]; then
            echo "上传失败！错误信息：$MESSAGE"
            exit 1
          fi
