name: AutoTestApp

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  upload-apk:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 检查 APK 文件是否存在
      - name: Check APK existence
        run: |
          if [ ! -f "apk/app-newest.apk" ]; then
            echo "APK 文件不存在！"
            exit 1
          fi

      # 3. 调用 Testin 登录接口并输出结果
      - name: 调用 Testin 登录接口
        run: |
          # 动态生成时间戳（当前时间的毫秒数）
          TIMESTAMP=$(date +%s%3N)
          
          # 构造请求体（JSON格式）
          REQUEST_DATA=$(cat <<EOF
          {
            "apikey": "0cc70ef717d01b48ebfef5868a60cdd9",
            "mkey": "usermanager",
            "op": "Login.login",
            "data": {
              "email": "nibingbing@testin.cn",
              "pwd": "e10adc3949ba59abbe56e057f20f883e"
            },
            "action": "user",
            "timestamp": ${TIMESTAMP}
          }
          EOF
          )
          
          # 发送 POST 请求并捕获响应
          RESPONSE=$(curl -s -X POST "https://openapizyy.testin.cn" \
            -H "Content-Type: application/json" \
            -d "$REQUEST_DATA")
          
          # 打印响应内容到日志
          echo "接口返回结果："
          echo "$RESPONSE"
