name: AutoTestApp

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  # 定义全局变量
  API_KEY: "3f7c06d07dfbf6cbb04618cb67e1e0d7"  # 在这里指定 API Key
  APP_FILE_PATH: "apk/app-newest.apk"         # 在这里指定 APP 文件路径
  JOB_ID: 4710                                # 在这里指定 Job ID，默认值为 4710
  PROJECT_ID: 1944025                         # 在这里指定 Project ID，默认值为 1944025
  EMAIL: "nibingbing@testin.cn"               # 在这里指定登录邮箱
  PASSWORD: "9624564eebc9a3c388f29598779f6215" # 在这里指定登录密码（建议使用加密方式存储）
  UPLOAD_ANDROID: "1"                         # 是否需要上传安卓 APK 文件？(1 表示是，0 表示否)
  UPLOAD_IOS: "0"                             # 是否需要上传 iOS IPA 文件？(1 表示是，0 表示否)

jobs:
  autotest-app:
    runs-on: ubuntu-latest
    steps:
      # 调试：打印 upload_app 的值
      - name: Debug upload_app value
        run: echo "是否需要上传APP->upload_app value:${{ env.UPLOAD_APP }}"

      # 1. 检出代码并禁用 SSL 验证
      - name: Checkout code 
        uses: actions/checkout@v4


      # 2. 检查 APP 文件是否存在，并解析文件类型
      - name: Check APP existence and parse file type
        id: app-info
        if: env.UPLOAD_ANDROID == '1' || env.UPLOAD_IOS == '1'
        run: |
          if [ ! -f "${{ env.APP_FILE_PATH }}" ]; then
            echo "APP 文件不存在！"
            exit 1
          fi

          # 提取文件名和扩展名
          FILE_NAME=$(basename "${{ env.APP_FILE_PATH }}")
          FILE_EXTENSION="${FILE_NAME##*.}"
          echo "文件名：$FILE_NAME"
          echo "文件扩展名：$FILE_EXTENSION"

          # 初始化 should_upload
          SHOULD_UPLOAD="false"

          # 判断文件类型并匹配上传条件
          if [[ "$FILE_EXTENSION" == "apk" && "${{ env.UPLOAD_ANDROID }}" == "1" ]]; then
            echo "检测到安卓 APK 文件，准备上传..."
            SHOULD_UPLOAD="true"
          elif [[ "$FILE_EXTENSION" == "ipa" && "${{ env.UPLOAD_IOS }}" == "1" ]]; then
            echo "检测到 iOS IPA 文件，准备上传..."
            SHOULD_UPLOAD="true"
          else
            echo "文件类型不符合上传条件，跳过上传。"
          fi

          # 设置环境变量
          echo "should_upload=$SHOULD_UPLOAD" >> $GITHUB_ENV

      # 3. 调用 Testin 登录接口并提取 result 值
      - name: 调用 Testin 登录接口
        id: login
        if: env.should_upload == 'true'
        run: |
          TIMESTAMP=$(date +%s%3N)
          REQUEST_DATA=$(cat <<EOF
          {
            "apikey": "${{ env.API_KEY }}",
            "mkey": "usermanager",
            "op": "Login.login",
            "data": {
              "email": "${{ env.EMAIL }}",
              "pwd": "${{ env.PASSWORD }}"
            },
            "action": "user",
            "timestamp": ${TIMESTAMP}
          }
          EOF
          )
          RESPONSE=$(curl -s -X POST "https://openapizyy.testin.cn" \
            -H "Content-Type: application/json" \
            -d "$REQUEST_DATA")
          echo "登录接口返回结果：$RESPONSE"
          RESULT=$(echo "$RESPONSE" | grep -o '"result":"[^"]*"' | awk -F':' '{print $2}' | sed 's/"//g')
          if [ -z "$RESULT" ]; then
            echo "未提取到有效的 result 值！"
            exit 1
          fi
          echo "::set-output name=result::$RESULT"
