name: AutoTestApp

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  upload-apk:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 检查 APK 文件是否存在
      - name: Check APK existence
        run: |
          if [ ! -f "apk/app-newest.apk" ]; then
            echo "APK 文件不存在！"
            exit 1
          fi

      # 3. 调用 Testin 登录接口并提取 result 值
      - name: 调用 Testin 登录接口
        id: login
        run: |
          TIMESTAMP=$(date +%s%3N)
          REQUEST_DATA=$(cat <<EOF
          {
            "apikey": "0cc70ef717d01b48ebfef5868a60cdd9",
            "mkey": "usermanager",
            "op": "Login.login",
            "data": {
              "email": "1033081356@qq.com",
              "pwd": "76fa3ac42ea40a439743e032c0463084"
            },
            "action": "user",
            "timestamp": ${TIMESTAMP}
          }
          EOF
          )
          RESPONSE=$(curl -s -X POST "https://openapizyy.testin.cn" \
            -H "Content-Type: application/json" \
            -d "$REQUEST_DATA")
          echo "登录接口返回结果：$RESPONSE"
          RESULT=$(echo "$RESPONSE" | grep -o '"result":"[^"]*"' | awk -F':' '{print $2}' | sed 's/"//g')
          if [ -z "$RESULT" ]; then
            echo "未提取到有效的 result 值！"
            exit 1
          fi
          echo "::set-output name=result::$RESULT"

      # 4. 使用提取到的 result 值上传 APK 文件
      - name: 上传 APK 文件
        run: |
          TIMESTAMP=$(date +%s%3N)
          SID=${{ steps.login.outputs.result }}
          UPLOAD_JSON='{"apikey":"0cc70ef717d01b48ebfef5868a60cdd9","timestamp":'"${TIMESTAMP}"',"sid":"'"${SID}"'","sig":"60ffc558f7c9c0110512392672b8cec2","mkey":"fs","action":"fs","op":"File.upload","data":{"suffix":"apk"}}'
          echo "构造的 UPLOAD-JSON 头：$UPLOAD_JSON"
          curl -v -X POST "https://openapizyy.testin.cn" \
            -H "UPLOAD-JSON: $UPLOAD_JSON" \
            -F "file=@apk/app-newest.apk"
