name: 测试云测Testin

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  upload-apk:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 检查 APK 文件是否存在
      - name: Check APK existence
        run: |
          if [ ! -f "apk/app-newest.apk" ]; then
            echo "APK 文件不存在！"
            exit 1
          fi

      # 3. 调用 Testin 登录接口并输出结果
      - name: 调用 Testin 登录接口
        env:
          API_KEY: ${{ secrets.TESTIN_API_KEY }}
          EMAIL: ${{ secrets.TESTIN_EMAIL }}
          PASSWORD: ${{ secrets.TESTIN_PASSWORD }}
        run: |
          # 动态生成时间戳（当前时间的毫秒数）
          TIMESTAMP=$(date +%s%3N)
          
          # 构造请求体（JSON格式）
          REQUEST_DATA=$(cat <<EOF
          {
            "apikey": "${API_KEY}",
            "mkey": "usermanager",
            "op": "Login.login",
            "data": {
              "email": "${EMAIL}",
              "pwd": "${PASSWORD}"
            },
            "action": "user",
            "timestamp": ${TIMESTAMP}
          }
          EOF
          )
          
          # 发送 POST 请求并捕获响应
          RESPONSE=$(curl -s -X POST "https://openapizyy.testin.cn" \
            -H "Content-Type: application/json" \
            -d "$REQUEST_DATA")
          
          # 打印响应内容到日志
          echo "接口返回结果："
          echo "$RESPONSE"
          
          # 可选：格式化 JSON 输出（需确保 jq 已安装）
          # echo "$RESPONSE" | jq .
